### ISSUE TITLE
Unable to connect

### ISSUE THREAD

**Issue by gbdomubpkm** [wdehoog/shoutcast-ubports#10]
The search for stations is done normally but it is very rare that I manage to connect to them. 9 times out of 10 I get the message that is attached to all my phones on the dev channel: OPO, BQ E5 HD, NEXUS 5. Is this normal at the current stage of development of the application ?

![Shoutcast error](https://user-images.githubusercontent.com/50362604/77795734-56036d00-706e-11ea-8888-5aa05091492c.png)

**Comment by wdehoog** [comment]
I am afraid it is problem with the SHOUTcast servers. Sometimes the search results indeed cause this error and sometimes repeating the same query results in working links.

If you think it is an isue with the code of the app you can take a look at the log file:
``` .cache/upstart/application-click-shoutcast-ubports.wdehoog_shoutcast-ubports_0.4.log```.

**Comment by gbdomubpkm** [comment]
Thank you for your answer. I'm not a developer, so there's nothing I can do. But having by interest looked at the log, everything indicates that some elements probably need to be updated. I see  'Binding loop detected for property "height", 'caller' is deprecated..

I can't interpret that.

**Comment by wdehoog** [comment]
The 'Binding loop ...' error is not a real problem (some qml related thing). The app will work even with this error in the log. 

If possible you can past the log in some pastebin site or attach it here so I can take a look.

You can also look at the logs while using the app:
```
tail -f .cache/upstart/application-click-shoutcast-ubports.wdehoog_shoutcast-ubports_0.4.log
```
maybe you can spot some pattern or try the urls shown in the log in a browser.

**Comment by gbdomubpkm** [comment]
https://paste.ubuntu.com/p/7TP337XdT4/

**Comment by wdehoog** [comment]
Thanks for the log. This url fails: ```http://yp.shoutcast.com/sbin/tunein-station.m3u?id=1674844```.
If you try it in browser you get a file containing:
```
#EXTM3U
```
nothing more. It is an empty playlist. Normally this file contains some stream urls. So SHOUTcast sends an empty list and there is nothing the app can do to fix this.

**Comment by gbdomubpkm** [comment]
Sorry i don't understand. Why SHOUTcast sends an empty list for some stations ? Stations that don't work in shoutcast are well functional because they work outside of Shoutcast..

**Comment by wdehoog** [comment]
Well I guess it is a bug in their system. Either they return stations for which they don't have the stream urls or they return the wrong id. 

Is there any particular station you tried?

**Comment by gbdomubpkm** [comment]
No. I look for a singer and then I choose a piece of music from it that is associated with a station.
But this  not new problem affects all Shoutcast users even if I'm the one who reported it.
I thought you could maybe solve the issue.
Thank you for considered the problem.

**Comment by gbdomubpkm** [comment]
I don't think there's any point in leaving that issue open.
