### ISSUE TITLE
How to donate ?

### ISSUE THREAD

**Issue by uratom962** [wdehoog/shoutcast-ubports#11]
Hi, I want to donate you a little money for support your dev. And your app is very good. But how to ? Via paypal or other money transfer service ?

**Comment by wdehoog** [comment]
Sorry but I do not accept donations. I really appreciate the gesture but it is a hobby that I am able to do because others are investing their time as well.

If someone wants to show appreciation for my work by a donation then may I suggest to support [UBports](https://ubports.com/donate).
