### ISSUE TITLE
Update the app to morph

### ISSUE THREAD

**Issue by gbdomubpkm** [wdehoog/shoutcast-ubports#13]
As Flas was, this very useful application deserves not to disappear and to be also updated to Morph because the vivid support won't last...

**Comment by cibersheep** [comment]
I'm pretty sure Shoutcast doesn't use Oxide so we're fine :)

Flas uses a webview for reasons far too long to be interesting ;)

**Comment by gbdomubpkm** [comment]
@cibersheep If there is nothing to be done on this side, then so much the better because this good application should not be forgotten !! Flas and Shoutcast make a great pair !

**Comment by wdehoog** [comment]
@gbdomubpkm as @cibersheep said there is no imminent problem with Oxide or Morph.

**Comment by gbdomubpkm** [comment]
Ok understood.
