### ISSUE TITLE
Missing all accented french characters + other bug

### ISSUE THREAD

**Issue by gbdomubpkm** [wdehoog/shoutcast-ubports#15]
Missing all accented french characters in texts.
![caract accent3](https://user-images.githubusercontent.com/50362604/86537737-aa31af00-bef1-11ea-8929-f38fa40eb5f5.png)
actuellement écouté
mots-clés

![caractaccent2](https://user-images.githubusercontent.com/50362604/86537818-13192700-bef2-11ea-97e3-4062a8a3b51d.png)

Paramètres
résultats
requête
réponse

![caract accent1](https://user-images.githubusercontent.com/50362604/86537888-976baa00-bef2-11ea-9da4-eadbac6251da.png)

... and this third screenshot to show the wrong position of the switch (encroachment) in portrait mode on the ' Afficher les logos / show logos' line.

**Comment by wdehoog** [comment]
They do show up when I run ```clickable desktop --dirty --lang fr_FR```. No idea why they would not be visible on your phone.

**Comment by gbdomubpkm** [comment]
Not on my phone, but on all my different phones (BQ E5 HD, NEXUS 5, OPO) regardless of the channel. 
 
The bug isn't new.  It appeared with the last update I think. But no french had reported it before.

**Comment by wdehoog** [comment]
The accents seem not converted when creating the click package. If I run msgfmt on the po file (ubuntu shell) the resulting mo file does have the accents but I am building the click package using clickable which runs msgfmt in some docker container. I'll keep digging.

**Comment by wdehoog** [comment]
A 'clean-build' made the accents appear. CMake caching behaves 'peculiar'. Anyway I have uploaded a new build which I hope works better.

**Comment by gbdomubpkm** [comment]
Thank you ! 👍 I confirm that the problem of accented characters is solved. I don't know why but even the help is now translated in french whereas in the 0.4 click, the help was in english (i can see this yet on my OPO not updated) ! 

It remains however as a bug the display 'parameters' in portrait mode (third screenshot) which is not correct.

**Comment by gbdomubpkm** [comment]
I saw that the bad display has been corrected in the click test  👍

**Comment by wdehoog** [comment]
I released 0.5 which address your issues. I renamed the app so you'll have to uninstall the old one (shoutcast-ubports) and install the new app (shoutcast-ut). Sorry for this.

**Comment by gbdomubpkm** [comment]
Good work 👍👋
