### ISSUE TITLE
Multi-line text in HelpPage.qml only shows first line

### ISSUE THREAD

**Issue by cibersheep** [wdehoog/shoutcast-ubports#3]
Multi-line like:
https://github.com/wdehoog/shoutcast-ubports/blob/master/shoutcast-ubports/pages/HelpPage.qml#L36
only shows first line in .pot file

**Comment by wdehoog** [comment]
Do you have any idea how it could be solved?

**Comment by wdehoog** [comment]
I added " \" after the lines and now all text is added to the po(t) files. However all formatting is lost. Hopefully someone knows a beter solution.

**Comment by cibersheep** [comment]
I'll take a look at it and I might be able to give a suggestion

**Comment by cibersheep** [comment]
I have created a new Pull Request, I have changed the Help and About pages a «little» bit.
I took out the html formatting and created a label for each line (it can also be made with a repeater but this approach have given me better results).
Feel free to change it to your liking or ditching it completely if doesn't fit your app

**Comment by wdehoog** [comment]
I tried to fix the issue by ending each part of the multiline text with "\n \". Now the qml and po(t) show the same text in the same formatting. I hope the translation tool you use supports it.

**Comment by cibersheep** [comment]
I'll check that

**Comment by cibersheep** [comment]
I have updated the Catalan file. I hope that helps.
Thank you
