### ISSUE TITLE
Can't scrolling when I search

### ISSUE THREAD

**Issue by uratom962** [wdehoog/shoutcast-ubports#9]
Hi,
when I search a radio like funk radio, I found a lot, but I can't scroll down.

**Comment by wdehoog** [comment]
Thanks for reporting. I think it is fixed in the latest commits. Can you build the app yourself to test it?
Or try this package: https://free01.thegood.cloud/s/CTyE4amwiZLxHgJ

**Comment by uratom962** [comment]
Hi I'm noob on UBPorts, I'm waiting your update on Openstore ...

**Comment by wdehoog** [comment]
Mmm. I'd like to know if it works before submitting it to the store. If you feel like helping I can explain how to install a click package on your phone to test it. 

1. Download it on your phone by clicking on the above link. 
2. Install it (from the terminal or an ssh shell or adb console) using:
```
pkcon --allow-untrusted install-local Downloads/shoutcast-ubports.wdehoog_0.4_all.click
```

**Comment by uratom962** [comment]
Hi I install, and now I have a bug all radio say me : Error : FAILED TO RETRIEVE STREAM URL.

**Comment by wdehoog** [comment]
Please see #10. It seems SHOUTcast server sends empty playlists (without any stream url).

**Comment by uratom962** [comment]
Solved. Now it work !
